dist: trusty
language: groovy
notifications:
  slack:
    secure: V4zpnowkZ3XRFooo3WCakpw9OPBK5aQVZWJ89sDT7BA+i9T/xAFIhAVLu6augnSgGXAXD2Lmbsyk6OKR6OdcTpnt1IMJKRboCEOtG1Bn1OrvaIck6cRl3asF+mXS/V6CZPmTvMfq5pSpa4sRb11NLKn8xPO8aGQTfgm2RZYmmFQ=
deploy:
  provider: releases
  api_key:
    secure: Ga7n9mC4TQUlK+yn7o/WeQbKR6m+0P4Q7Ijlh8nNAJZ8Bgxx9KcDWe/UE7BOjfzbVwYpSnlViRcG4fs+Q7VvUIeRSu+bRHe0S5zTag0PqHe4OfagaXrgQ+vRyqkdmPUMnEvku7qYR0jonX3zrnJdSs1Ue31lZyRaCflMfX5dpBU=
  file: build/libs/gradle-xld-plugin-0.6.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/gradle-xld-plugin
