dist: trusty
language: groovy
notifications:
  hipchat:
    rooms:
      secure: BRxyikZ3/l8yGg63JU/oa7YETcMUhcHXQHFf4EF7kdD4hSgqhmHHlCMjDFcx84rTTf1CrcpiKVJfn1LPFADKr3QMEaatx9nWCPs1iHbZBfRhUJPVaG/1kN0cVyU5vz0v2KY2hx5FTnoecvL6ihdhpnWoWPZZxfDGT7t6uhAElbg=
deploy:
  provider: releases
  api_key:
    secure: Ga7n9mC4TQUlK+yn7o/WeQbKR6m+0P4Q7Ijlh8nNAJZ8Bgxx9KcDWe/UE7BOjfzbVwYpSnlViRcG4fs+Q7VvUIeRSu+bRHe0S5zTag0PqHe4OfagaXrgQ+vRyqkdmPUMnEvku7qYR0jonX3zrnJdSs1Ue31lZyRaCflMfX5dpBU=
  file: build/libs/gradle-xld-plugin-0.6.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/gradle-xld-plugin
