dist: trusty
language: groovy
notifications:
  hipchat:
    rooms:
      secure: BRxyikZ3/l8yGg63JU/oa7YETcMUhcHXQHFf4EF7kdD4hSgqhmHHlCMjDFcx84rTTf1CrcpiKVJfn1LPFADKr3QMEaatx9nWCPs1iHbZBfRhUJPVaG/1kN0cVyU5vz0v2KY2hx5FTnoecvL6ihdhpnWoWPZZxfDGT7t6uhAElbg=
deploy:
  provider: releases
  api_key:
    secure: MRLNi3AMqraAqSHkCQIcJtO4fc7MNsJuiclTDUmgkeUsP1Zt4qyMm7S5x73IsPMwEvDqtTvhnNDhf4B2juEeE9D4TdjMbBhV56iptFzwfIpVzF3sV8gzvki6P3jJKylC9gldgkG03gQae81ruFrWpIJIyrOJjG3Kg1Ms7+ZoIXw=
  file: build/libs/gradle-xld-plugin-0.6.2.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/gradle-xld-plugin
